<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Images\RentAFriendLogo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\Image\**" />
    <Compile Remove="Resources\Новая папка\**" />
    <EmbeddedResource Remove="Resources\Image\**" />
    <EmbeddedResource Remove="Resources\Новая папка\**" />
    <None Remove="Resources\Image\**" />
    <None Remove="Resources\Новая папка\**" />
    <Page Remove="Resources\Image\**" />
    <Page Remove="Resources\Новая папка\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\close_ico.png" />
    <None Remove="Resources\Icons\delete_ico.png" />
    <None Remove="Resources\Icons\exit.png" />
    <None Remove="Resources\Icons\open_ico.png" />
    <None Remove="Resources\Images\rentiIco.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Images\RentAFriendLogo.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Models\UserInfoItem.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\close_ico.png" />
    <Resource Include="Resources\Icons\delete_ico.png" />
    <Resource Include="Resources\Icons\exit.png" />
    <Resource Include="Resources\Icons\open_ico.png" />
    <Resource Include="Resources\Images\rentiIco.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
